### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: minioSelectParquet.DefaultSource

### ISSUE THREAD

**Issue by NithK45** [minio/spark-select#5]
I'm reading parquet files in s3 from spark-shell, by adding spark-select fat jar.

**spark_home/bin/spark-shell --jars /home/ec2-user/spark-select-assembly-2.0.jar**
```
import org.apache.spark.sql._
import org.apache.spark.sql.types._
import io.minio.spark.select._

val schema = StructType(
      List(
        StructField("member_ind", StringType, true),
        StructField("solicit_ind", StringType, true)
      )
    )

val df = spark.read.format("minioSelectParquet").schema(schema).load("s3a://bucket/prefix/")
```

But this throws me the class not found exception even after adding the jar and importing in the spark-shell. 

Any thoughts?

> java.lang.ClassNotFoundException: Failed to find data source: minioSelectParquet. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:644)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:193)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:177)
  ... 53 elided
Caused by: java.lang.ClassNotFoundException: minioSelectParquet.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:627)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20$$anonfun$apply$12.apply(DataSource.scala:627)
  at scala.util.Try$.apply(Try.scala:192)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:627)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$20.apply(DataSource.scala:627)
  at scala.util.Try.orElse(Try.scala:84)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:627)
  ... 55 more

**Comment by harshavardhana** [comment]
Thanks have you tried the default approach of using the spark-packages directly ?

**Comment by harshavardhana** [comment]
Seems to be working fine for me locally

```
~ spark-shell --jars /home/harsha/repos/spark-select/target/scala-2.11/spark-select-assembly-2.0.jar 
2019-03-07 11:08:50 WARN  Utils:66 - Your hostname, backspace resolves to a loopback address: 127.0.1.1; using 192.168.1.157 instead (on interface wlp59s0)
2019-03-07 11:08:50 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2019-03-07 11:08:50 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://backspace.hsd1.ca.comcast.net:4040
Spark context available as 'sc' (master = local[*], app id = local-1551985737143).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.1
      /_/
         
Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load examples/parquet.scala
Loading examples/parquet.scala...
import org.apache.spark.sql._
import org.apache.spark.sql.types._
defined object app

scala> app.main(Array(""))
```

```
~ spark-shell --packages io.minio:spark-select_2.11:2.0
...

2019-03-07 11:07:12 WARN  Utils:66 - Your hostname, backspace resolves to a loopback address: 127.0.1.1; using 192.168.1.157 instead (on interface wlp59s0)
2019-03-07 11:07:12 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2019-03-07 11:07:12 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://backspace.hsd1.ca.comcast.net:4040
Spark context available as 'sc' (master = local[*], app id = local-1551985639565).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.3.1
      /_/
         
Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load examples/parquet.scala
Loading examples/parquet.scala...
import org.apache.spark.sql._
import org.apache.spark.sql.types._
defined object app

scala> app.main(Array(""))
```

**Comment by NithK45** [comment]
I'm still getting the same error and trying to troubleshoot.
Additional details: I am running on the ec2-instance spark 2.4.0 cluster, querying parquet files in s3.

I have generated fat jar by running "sbt assembly". I had to change the build.sbt from 

```assemblyMergeStrategy in assembly := {
  case "META-INF/io.netty.versions.properties" => MergeStrategy.concat
  case x =>
    val oldStrategy = (assemblyMergeStrategy in assembly).value
    oldStrategy(x)
}```

To 

```assemblyMergeStrategy in assembly := {
  case "META-INF/io.netty.versions.properties" => MergeStrategy.concat
  case x =>
    MergeStrategy.first
}```

to get around below build error. But i think this change does not impact the use of jar.

```
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-codec-http\jars\netty-codec-http-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-codec\jars\netty-codec-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-transport\jars\netty-transport-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-buffer\jars\netty-buffer-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-common\jars\netty-common-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-resolver\jars\netty-resolver-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\nkotha\.ivy2\cache\io.netty\netty-handler\jars\netty-handler-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] Total time: 49 s, completed 08/03/2019 2:58:06 PM
```
I'm building a sample application with above code and run it as a jar to see if that works.

**Comment by harshavardhana** [comment]
I think changing merge strategy can cause issues @NithK45 would it possible to use 

```
spark-shell --packages io.minio:spark-select_2.11:2.0
```

just use?

**Comment by NithK45** [comment]
Sorry, I did try that. I'm getting a connection time out on ec2 due to vpn i think.

**Comment by harshavardhana** [comment]
@NithK45 I tried with spark 2.4.0 as well seems to work fine.

```
~ spark-shell --jars /home/harsha/repos/spark-select/target/scala-2.11/spark-select-assembly-2.0.jar
Spark context Web UI available at http://192.168.43.208:4040
Spark context available as 'sc' (master = local[*], app id = local-1552069463981).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.0
      /_/
         
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load examples/parquet.scala
Loading examples/parquet.scala...
import org.apache.spark.sql._
import org.apache.spark.sql.types._
defined object app

scala> app.main(Array(""))
+-------+---+                                                                   
|   name|age|
+-------+---+
|Michael| 31|
|   Andy| 30|
| Justin| 19|
+-------+---+

()
+-------+---+
|   name|age|
+-------+---+
|Michael| 31|
|   Andy| 30|
+-------+---+

()

scala>
```

**Comment by harshavardhana** [comment]
Have you tried this example ?

```
import org.apache.spark.sql._
import org.apache.spark.sql.types._

val schema = StructType(
      List(
        StructField("member_ind", StringType, true),
        StructField("solicit_ind", StringType, true)
      )
    )

val df = spark.read.format("minioSelectParquet").schema(schema).load("s3a://bucket/prefix/")
```

The only change is to avoid doing 
```
import io.minio.spark.select._
```

**Comment by harshavardhana** [comment]
Closing this for now as working..
